package com.example.gramavaxi

fun getAnimals(): List<Animal> {
    val tumkur = 1; val kolar = 2; val blr = 3

    fun vax(vararg pairs: Pair<String, Pair<String, VaccineStatus>>): List<VaccineRecord> =
        pairs.map { VaccineRecord(it.first, it.second.first, it.second.second) }

    return listOf(
        // ── TUMKUR (Camp 1) — 25 animals ──────────────────────────────────
        Animal(1,"Lakshmi",Species.COW,"Malnad Gidda","5 yrs","Female","GV-T001","Ramesh K.","Doddapura",tumkur,VaccineStatus.DONE,
            vax("FMD" to ("Jun 2024" to VaccineStatus.DONE),"PPR" to ("Sep 2024" to VaccineStatus.DONE),"HS" to ("Jan 2025" to VaccineStatus.SCHEDULED)),"320 kg","Reddish-brown"),
        Animal(2,"Rani",Species.COW,"Hallikar","4 yrs","Female","GV-T002","Suresh M.","Honnapura",tumkur,VaccineStatus.DUE_SOON,
            vax("FMD" to ("Apr 2024" to VaccineStatus.DONE),"BQ" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"295 kg","White"),
        Animal(3,"Champa",Species.COW,"Khillar","6 yrs","Female","GV-T003","Nagaraj B.","Siddapura",tumkur,VaccineStatus.OVERDUE,
            vax("FMD" to ("Mar 2024" to VaccineStatus.DONE),"PPR" to ("Oct 2024" to VaccineStatus.OVERDUE)),"340 kg","Grey"),
        Animal(4,"Gowri",Species.COW,"Malnad Gidda","3 yrs","Female","GV-T004","Manjunath R.","Tumkur",tumkur,VaccineStatus.DONE,
            vax("FMD" to ("Jul 2024" to VaccineStatus.DONE),"HS" to ("Nov 2024" to VaccineStatus.DONE)),"270 kg","Brown"),
        Animal(5,"Savitri",Species.COW,"Ongole","7 yrs","Female","GV-T005","Raju S.","Kyatanahalli",tumkur,VaccineStatus.DONE,
            vax("FMD" to ("May 2024" to VaccineStatus.DONE),"BQ" to ("Aug 2024" to VaccineStatus.DONE)),"380 kg","White-grey"),
        Animal(6,"Nandini",Species.BUFFALO,"Murrah","4 yrs","Female","GV-T006","Puttaiah H.","Gubbi",tumkur,VaccineStatus.DUE_SOON,
            vax("HS" to ("Jun 2024" to VaccineStatus.DONE),"FMD" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"410 kg","Black"),
        Animal(7,"Kauvery",Species.BUFFALO,"Surti","5 yrs","Female","GV-T007","Siddaraju K.","Tiptur",tumkur,VaccineStatus.DONE,
            vax("HS" to ("May 2024" to VaccineStatus.DONE),"BQ" to ("Sep 2024" to VaccineStatus.DONE)),"395 kg","Dark grey"),
        Animal(8,"Sindhu",Species.BUFFALO,"Jaffarabadi","6 yrs","Female","GV-T008","Venkatesha P.","Tumkur",tumkur,VaccineStatus.OVERDUE,
            vax("HS" to ("Feb 2024" to VaccineStatus.DONE),"FMD" to ("Sep 2024" to VaccineStatus.OVERDUE)),"430 kg","Black"),
        Animal(9,"Chandra",Species.GOAT,"Beetal","2 yrs","Male","GV-T009","Ramesha G.","Sira",tumkur,VaccineStatus.DONE,
            vax("PPR" to ("Aug 2024" to VaccineStatus.DONE),"ET" to ("Nov 2024" to VaccineStatus.DONE)),"38 kg","White-black"),
        Animal(10,"Veera",Species.GOAT,"Osmanabadi","3 yrs","Male","GV-T010","Krishnamurthy V.","Madhugiri",tumkur,VaccineStatus.DONE,
            vax("PPR" to ("Jul 2024" to VaccineStatus.DONE),"ET" to ("Oct 2024" to VaccineStatus.DONE)),"42 kg","Brown"),
        Animal(11,"Bhagya",Species.GOAT,"Malabari","2 yrs","Female","GV-T011","Nagesh T.","Koratagere",tumkur,VaccineStatus.DUE_SOON,
            vax("PPR" to ("May 2024" to VaccineStatus.DONE),"ET" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"35 kg","Black"),
        Animal(12,"Meena",Species.GOAT,"Boer Cross","1 yr","Female","GV-T012","Basavaraju N.","Pavagada",tumkur,VaccineStatus.DONE,
            vax("PPR" to ("Sep 2024" to VaccineStatus.DONE)),"28 kg","White"),
        Animal(13,"Rajappa",Species.SHEEP,"Deccani","3 yrs","Male","GV-T013","Thippeswamy L.","Turuvekere",tumkur,VaccineStatus.DONE,
            vax("PPR" to ("Jun 2024" to VaccineStatus.DONE),"ET" to ("Oct 2024" to VaccineStatus.DONE)),"45 kg","White"),
        Animal(14,"Shanti",Species.SHEEP,"Nellore","4 yrs","Female","GV-T014","Narayana S.","Gubbi",tumkur,VaccineStatus.DUE_SOON,
            vax("PPR" to ("Apr 2024" to VaccineStatus.DONE),"ET" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"48 kg","White-cream"),
        Animal(15,"Basavanna",Species.SHEEP,"Hassan","2 yrs","Male","GV-T015","Gundappa R.","Sira",tumkur,VaccineStatus.DONE,
            vax("PPR" to ("Aug 2024" to VaccineStatus.DONE)),"32 kg","Brown-white"),
        Animal(16,"Moti",Species.SHEEP,"Deccani","5 yrs","Female","GV-T016","Sannappa M.","Tiptur",tumkur,VaccineStatus.OVERDUE,
            vax("PPR" to ("Jan 2024" to VaccineStatus.DONE),"ET" to ("Aug 2024" to VaccineStatus.OVERDUE)),"52 kg","White"),
        Animal(17,"Ducky",Species.DUCK,"Khaki Campbell","1 yr","Female","GV-T017","Ramu K.","Doddapura",tumkur,VaccineStatus.DONE,
            vax("Duck Plague" to ("Oct 2024" to VaccineStatus.DONE)),"2.1 kg","Khaki-brown"),
        Animal(18,"Pandu",Species.DUCK,"Indian Runner","1 yr","Male","GV-T018","Srinivas B.","Honnapura",tumkur,VaccineStatus.DONE,
            vax("Duck Plague" to ("Sep 2024" to VaccineStatus.DONE)),"1.8 kg","White"),
        Animal(19,"Kali",Species.HEN,"Kadaknath","2 yrs","Female","GV-T019","Munivenkatappa H.","Tumkur",tumkur,VaccineStatus.DONE,
            vax("RD" to ("Aug 2024" to VaccineStatus.DONE),"Marek" to ("Jan 2024" to VaccineStatus.DONE)),"2.8 kg","Black"),
        Animal(20,"Sona",Species.HEN,"Gramapriya","1 yr","Female","GV-T020","Lokesh P.","Kyatanahalli",tumkur,VaccineStatus.DUE_SOON,
            vax("RD" to ("Jun 2024" to VaccineStatus.DONE),"IB" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"1.9 kg","Golden"),
        Animal(21,"Babu",Species.PIG,"Desi Cross","2 yrs","Male","GV-T021","Patel R.","Gubbi",tumkur,VaccineStatus.DONE,
            vax("CSF" to ("Jul 2024" to VaccineStatus.DONE),"FMD" to ("Oct 2024" to VaccineStatus.DONE)),"85 kg","Pink-black"),
        Animal(22,"Mala",Species.PIG,"Large White Yorkshire","1 yr","Female","GV-T022","Devappa K.","Siddapura",tumkur,VaccineStatus.DONE,
            vax("CSF" to ("Aug 2024" to VaccineStatus.DONE)),"72 kg","White-pink"),
        Animal(23,"Bunty",Species.RABBIT,"New Zealand White","8 mo","Male","GV-T023","Eranna S.","Madhugiri",tumkur,VaccineStatus.DONE,
            vax("Myxoma" to ("Nov 2024" to VaccineStatus.DONE)),"3.2 kg","White"),
        Animal(24,"Manju",Species.GOAT,"Sangamneri","3 yrs","Female","GV-T024","Yellappa N.","Sira",tumkur,VaccineStatus.SCHEDULED,
            vax("PPR" to ("Oct 2024" to VaccineStatus.DONE),"ET" to ("Jan 2025" to VaccineStatus.SCHEDULED)),"39 kg","White-brown"),
        Animal(25,"Rathi",Species.SHEEP,"Bannur","4 yrs","Female","GV-T025","Papaiah G.","Turuvekere",tumkur,VaccineStatus.DONE,
            vax("PPR" to ("Jul 2024" to VaccineStatus.DONE),"ET" to ("Nov 2024" to VaccineStatus.DONE)),"50 kg","White-tan"),

        // ── KOLAR (Camp 2) — 25 animals ────────────────────────────────────
        Animal(26,"Ambika",Species.COW,"Hallikar","5 yrs","Female","GV-K001","Venkatesh A.","Kolar",kolar,VaccineStatus.DONE,
            vax("FMD" to ("May 2024" to VaccineStatus.DONE),"HS" to ("Sep 2024" to VaccineStatus.DONE)),"305 kg","Cream-white"),
        Animal(27,"Saraswati",Species.COW,"Khillar","6 yrs","Female","GV-K002","Narasimha M.","Bangarpet",kolar,VaccineStatus.DUE_SOON,
            vax("FMD" to ("Apr 2024" to VaccineStatus.DONE),"BQ" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"328 kg","Grey-white"),
        Animal(28,"Kamakshi",Species.COW,"Malnad Gidda","4 yrs","Female","GV-K003","Krishnappa V.","Srinivaspur",kolar,VaccineStatus.DONE,
            vax("FMD" to ("Jun 2024" to VaccineStatus.DONE),"PPR" to ("Oct 2024" to VaccineStatus.DONE)),"285 kg","Brown"),
        Animal(29,"Tulasi",Species.COW,"Holstein Cross","3 yrs","Female","GV-K004","Subbaiah R.","Malur",kolar,VaccineStatus.OVERDUE,
            vax("FMD" to ("Mar 2024" to VaccineStatus.DONE),"HS" to ("Aug 2024" to VaccineStatus.OVERDUE)),"355 kg","Black-white"),
        Animal(30,"Hemavathi",Species.COW,"Ongole","7 yrs","Female","GV-K005","Muniraju L.","Kolar",kolar,VaccineStatus.DONE,
            vax("FMD" to ("Jul 2024" to VaccineStatus.DONE),"BQ" to ("Nov 2024" to VaccineStatus.DONE)),"390 kg","White"),
        Animal(31,"Kaveri",Species.BUFFALO,"Murrah","5 yrs","Female","GV-K006","Shankaraiah N.","Robertsonpet",kolar,VaccineStatus.DONE,
            vax("HS" to ("May 2024" to VaccineStatus.DONE),"FMD" to ("Sep 2024" to VaccineStatus.DONE)),"425 kg","Black"),
        Animal(32,"Sharada",Species.BUFFALO,"Nili-Ravi","4 yrs","Female","GV-K007","Govindappa T.","Bangarpet",kolar,VaccineStatus.DUE_SOON,
            vax("HS" to ("Jun 2024" to VaccineStatus.DONE),"BQ" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"408 kg","Dark black"),
        Animal(33,"Vijaya",Species.BUFFALO,"Surti","6 yrs","Female","GV-K008","Papaiah K.","Kolar",kolar,VaccineStatus.DONE,
            vax("HS" to ("May 2024" to VaccineStatus.DONE),"FMD" to ("Aug 2024" to VaccineStatus.DONE)),"418 kg","Grey-black"),
        Animal(34,"Bheema",Species.GOAT,"Beetal","3 yrs","Male","GV-K009","Anjinappa R.","Malur",kolar,VaccineStatus.DONE,
            vax("PPR" to ("Jul 2024" to VaccineStatus.DONE),"ET" to ("Nov 2024" to VaccineStatus.DONE)),"44 kg","Black-white"),
        Animal(35,"Shakuntala",Species.GOAT,"Osmanabadi","2 yrs","Female","GV-K010","Somashekhar V.","Srinivaspur",kolar,VaccineStatus.SCHEDULED,
            vax("PPR" to ("Sep 2024" to VaccineStatus.DONE),"ET" to ("Jan 2025" to VaccineStatus.SCHEDULED)),"36 kg","Brown-white"),
        Animal(36,"Durga",Species.GOAT,"Malabari","3 yrs","Female","GV-K011","Nagaraj P.","Kolar",kolar,VaccineStatus.DONE,
            vax("PPR" to ("Jun 2024" to VaccineStatus.DONE),"ET" to ("Oct 2024" to VaccineStatus.DONE)),"40 kg","Black"),
        Animal(37,"Parvati",Species.GOAT,"Boer Cross","1 yr","Female","GV-K012","Raju L.","Bangarpet",kolar,VaccineStatus.DUE_SOON,
            vax("PPR" to ("Jul 2024" to VaccineStatus.DONE),"ET" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"30 kg","White-brown"),
        Animal(38,"Arjuna",Species.SHEEP,"Deccani","4 yrs","Male","GV-K013","Basappa H.","Robertsonpet",kolar,VaccineStatus.DONE,
            vax("PPR" to ("May 2024" to VaccineStatus.DONE),"ET" to ("Sep 2024" to VaccineStatus.DONE)),"49 kg","White"),
        Animal(39,"Subhadra",Species.SHEEP,"Nellore","3 yrs","Female","GV-K014","Venugopal S.","Malur",kolar,VaccineStatus.DONE,
            vax("PPR" to ("Jun 2024" to VaccineStatus.DONE),"ET" to ("Oct 2024" to VaccineStatus.DONE)),"44 kg","Cream"),
        Animal(40,"Dharani",Species.SHEEP,"Hassan","2 yrs","Female","GV-K015","Siddaraju B.","Kolar",kolar,VaccineStatus.OVERDUE,
            vax("PPR" to ("Feb 2024" to VaccineStatus.DONE),"ET" to ("Aug 2024" to VaccineStatus.OVERDUE)),"36 kg","White-brown"),
        Animal(41,"Ganga",Species.SHEEP,"Deccani","5 yrs","Female","GV-K016","Thimmappa N.","Srinivaspur",kolar,VaccineStatus.DONE,
            vax("PPR" to ("May 2024" to VaccineStatus.DONE),"ET" to ("Sep 2024" to VaccineStatus.DONE)),"55 kg","White"),
        Animal(42,"Pinky",Species.DUCK,"Khaki Campbell","1 yr","Female","GV-K017","Rangaswamy V.","Bangarpet",kolar,VaccineStatus.DONE,
            vax("Duck Plague" to ("Nov 2024" to VaccineStatus.DONE)),"2.0 kg","Khaki"),
        Animal(43,"Chotu",Species.DUCK,"Indian Runner","8 mo","Male","GV-K018","Lakshmana T.","Kolar",kolar,VaccineStatus.DUE_SOON,
            vax("Duck Plague" to ("Jul 2024" to VaccineStatus.DONE),"CC" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"1.7 kg","White-brown"),
        Animal(44,"Roja",Species.HEN,"Gramapriya","1 yr","Female","GV-K019","Muniswamy R.","Malur",kolar,VaccineStatus.DONE,
            vax("RD" to ("Sep 2024" to VaccineStatus.DONE),"IB" to ("Nov 2024" to VaccineStatus.DONE)),"2.1 kg","Reddish-brown"),
        Animal(45,"Myna",Species.HEN,"Kadaknath","2 yrs","Female","GV-K020","Yerriswamy K.","Robertsonpet",kolar,VaccineStatus.DONE,
            vax("RD" to ("Jul 2024" to VaccineStatus.DONE),"Marek" to ("Mar 2024" to VaccineStatus.DONE)),"2.9 kg","Black-shiny"),
        Animal(46,"Gopi",Species.PIG,"Hampshire Cross","2 yrs","Male","GV-K021","Nanjappa G.","Kolar",kolar,VaccineStatus.DUE_SOON,
            vax("CSF" to ("Jun 2024" to VaccineStatus.DONE),"FMD" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"90 kg","Black-white"),
        Animal(47,"Rukmini",Species.GOAT,"Sangamneri","4 yrs","Female","GV-K022","Hanumanthappa T.","Bangarpet",kolar,VaccineStatus.DONE,
            vax("PPR" to ("Aug 2024" to VaccineStatus.DONE),"ET" to ("Nov 2024" to VaccineStatus.DONE)),"42 kg","White"),
        Animal(48,"Aruna",Species.SHEEP,"Bannur","3 yrs","Female","GV-K023","Somashekar L.","Srinivaspur",kolar,VaccineStatus.DONE,
            vax("PPR" to ("Jun 2024" to VaccineStatus.DONE),"ET" to ("Oct 2024" to VaccineStatus.DONE)),"47 kg","White-cream"),
        Animal(49,"Fluffy",Species.RABBIT,"Soviet Chinchilla","6 mo","Female","GV-K024","Devaraju N.","Malur",kolar,VaccineStatus.DONE,
            vax("Myxoma" to ("Oct 2024" to VaccineStatus.DONE)),"2.8 kg","Grey"),
        Animal(50,"Kothari",Species.BUFFALO,"Murrah","3 yrs","Male","GV-K025","Channakeshava B.","Kolar",kolar,VaccineStatus.SCHEDULED,
            vax("HS" to ("Sep 2024" to VaccineStatus.DONE),"FMD" to ("Jan 2025" to VaccineStatus.SCHEDULED)),"480 kg","Black"),

        // ── BANGALORE (Camp 3) — 25 animals ────────────────────────────────
        Animal(51,"Padmavathi",Species.COW,"Jersey Cross","4 yrs","Female","GV-B001","Suresh B.","Anekal",blr,VaccineStatus.DONE,
            vax("FMD" to ("Jun 2024" to VaccineStatus.DONE),"HS" to ("Oct 2024" to VaccineStatus.DONE)),"310 kg","Fawn"),
        Animal(52,"Vasantha",Species.COW,"Holstein Friesian","5 yrs","Female","GV-B002","Nanjundaswamy V.","Anekal",blr,VaccineStatus.DUE_SOON,
            vax("FMD" to ("May 2024" to VaccineStatus.DONE),"PPR" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"370 kg","Black-white"),
        Animal(53,"Shakunthala",Species.COW,"Malnad Gidda","3 yrs","Female","GV-B003","Ramappa H.","Anekal",blr,VaccineStatus.DONE,
            vax("FMD" to ("Jul 2024" to VaccineStatus.DONE),"BQ" to ("Nov 2024" to VaccineStatus.DONE)),"275 kg","Brown"),
        Animal(54,"Prabha",Species.COW,"Khillar","6 yrs","Female","GV-B004","Krishnegowda M.","Doddaballapur",blr,VaccineStatus.OVERDUE,
            vax("FMD" to ("Feb 2024" to VaccineStatus.DONE),"HS" to ("Aug 2024" to VaccineStatus.OVERDUE)),"335 kg","Grey"),
        Animal(55,"Mahadevi",Species.COW,"Ongole","8 yrs","Female","GV-B005","Channappa R.","Nelamangala",blr,VaccineStatus.DONE,
            vax("FMD" to ("Jun 2024" to VaccineStatus.DONE),"BQ" to ("Oct 2024" to VaccineStatus.DONE)),"400 kg","White"),
        Animal(56,"Revathi",Species.BUFFALO,"Murrah","5 yrs","Female","GV-B006","Lingappa T.","Doddaballapur",blr,VaccineStatus.DONE,
            vax("HS" to ("May 2024" to VaccineStatus.DONE),"FMD" to ("Sep 2024" to VaccineStatus.DONE)),"435 kg","Black"),
        Animal(57,"Bhuvaneshwari",Species.BUFFALO,"Nili-Ravi","4 yrs","Female","GV-B007","Shivappa K.","Nelamangala",blr,VaccineStatus.DUE_SOON,
            vax("HS" to ("Jun 2024" to VaccineStatus.DONE),"BQ" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"415 kg","Dark black"),
        Animal(58,"Janaki",Species.BUFFALO,"Surti","7 yrs","Female","GV-B008","Boraiah N.","Anekal",blr,VaccineStatus.DONE,
            vax("HS" to ("Apr 2024" to VaccineStatus.DONE),"FMD" to ("Aug 2024" to VaccineStatus.DONE)),"440 kg","Black-grey"),
        Animal(59,"Mahesh",Species.GOAT,"Beetal","3 yrs","Male","GV-B009","Papaiah S.","Doddaballapur",blr,VaccineStatus.DONE,
            vax("PPR" to ("Aug 2024" to VaccineStatus.DONE),"ET" to ("Nov 2024" to VaccineStatus.DONE)),"46 kg","Black-white"),
        Animal(60,"Manjula",Species.GOAT,"Osmanabadi","2 yrs","Female","GV-B010","Veeranna B.","Nelamangala",blr,VaccineStatus.DUE_SOON,
            vax("PPR" to ("Jul 2024" to VaccineStatus.DONE),"ET" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"38 kg","Brown"),
        Animal(61,"Nagamma",Species.GOAT,"Malabari","4 yrs","Female","GV-B011","Nanjappa L.","Anekal",blr,VaccineStatus.DONE,
            vax("PPR" to ("Jun 2024" to VaccineStatus.DONE),"ET" to ("Oct 2024" to VaccineStatus.DONE)),"43 kg","Black"),
        Animal(62,"Sunanda",Species.GOAT,"Boer Cross","2 yrs","Female","GV-B012","Kempaiah R.","Doddaballapur",blr,VaccineStatus.DONE,
            vax("PPR" to ("Sep 2024" to VaccineStatus.DONE)),"32 kg","White-brown"),
        Animal(63,"Krishnappa",Species.SHEEP,"Deccani","4 yrs","Male","GV-B013","Boranna T.","Nelamangala",blr,VaccineStatus.DUE_SOON,
            vax("PPR" to ("Apr 2024" to VaccineStatus.DONE),"ET" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"51 kg","White"),
        Animal(64,"Sharada",Species.SHEEP,"Nellore","3 yrs","Female","GV-B014","Manjappa N.","Anekal",blr,VaccineStatus.DONE,
            vax("PPR" to ("Jul 2024" to VaccineStatus.DONE),"ET" to ("Nov 2024" to VaccineStatus.DONE)),"46 kg","Cream"),
        Animal(65,"Kamala",Species.SHEEP,"Hassan","2 yrs","Female","GV-B015","Honnappa V.","Doddaballapur",blr,VaccineStatus.DONE,
            vax("PPR" to ("Aug 2024" to VaccineStatus.DONE)),"38 kg","White-brown"),
        Animal(66,"Subbamma",Species.SHEEP,"Bannur","5 yrs","Female","GV-B016","Yellappa M.","Nelamangala",blr,VaccineStatus.OVERDUE,
            vax("PPR" to ("Feb 2024" to VaccineStatus.DONE),"ET" to ("Sep 2024" to VaccineStatus.OVERDUE)),"56 kg","White"),
        Animal(67,"Donald",Species.DUCK,"Khaki Campbell","1 yr","Male","GV-B017","Srinivasa B.","Anekal",blr,VaccineStatus.DONE,
            vax("Duck Plague" to ("Oct 2024" to VaccineStatus.DONE)),"2.3 kg","Khaki-brown"),
        Animal(68,"Meenu",Species.DUCK,"Muscovy","8 mo","Female","GV-B018","Narayana R.","Doddaballapur",blr,VaccineStatus.DUE_SOON,
            vax("Duck Plague" to ("Aug 2024" to VaccineStatus.DONE),"CC" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"2.5 kg","White-black"),
        Animal(69,"Priya",Species.HEN,"Gramapriya","1 yr","Female","GV-B019","Veeresh T.","Nelamangala",blr,VaccineStatus.DONE,
            vax("RD" to ("Sep 2024" to VaccineStatus.DONE),"IB" to ("Nov 2024" to VaccineStatus.DONE)),"2.2 kg","Brown"),
        Animal(70,"Chikki",Species.HEN,"Kadaknath","2 yrs","Female","GV-B020","Kemparaju H.","Anekal",blr,VaccineStatus.SCHEDULED,
            vax("RD" to ("Sep 2024" to VaccineStatus.DONE),"Marek" to ("Feb 2024" to VaccineStatus.DONE),"IB" to ("Jan 2025" to VaccineStatus.SCHEDULED)),"2.7 kg","Black"),
        Animal(71,"Ramu",Species.PIG,"Desi Cross","2 yrs","Male","GV-B021","Basavaraju K.","Doddaballapur",blr,VaccineStatus.DONE,
            vax("CSF" to ("Jul 2024" to VaccineStatus.DONE),"FMD" to ("Nov 2024" to VaccineStatus.DONE)),"88 kg","Pink-grey"),
        Animal(72,"Gomathi",Species.GOAT,"Sangamneri","3 yrs","Female","GV-B022","Dyavanaiah N.","Nelamangala",blr,VaccineStatus.DONE,
            vax("PPR" to ("Aug 2024" to VaccineStatus.DONE),"ET" to ("Dec 2024" to VaccineStatus.DONE)),"41 kg","White-brown"),
        Animal(73,"Shreya",Species.SHEEP,"Deccani","3 yrs","Female","GV-B023","Rangappa V.","Anekal",blr,VaccineStatus.DONE,
            vax("PPR" to ("Jul 2024" to VaccineStatus.DONE),"ET" to ("Oct 2024" to VaccineStatus.DONE)),"48 kg","White"),
        Animal(74,"Snowball",Species.RABBIT,"New Zealand White","5 mo","Male","GV-B024","Shivakumar T.","Doddaballapur",blr,VaccineStatus.DONE,
            vax("Myxoma" to ("Nov 2024" to VaccineStatus.DONE)),"2.5 kg","White"),
        Animal(75,"Yamuna",Species.BUFFALO,"Murrah","6 yrs","Female","GV-B025","Nagarajappa K.","Nelamangala",blr,VaccineStatus.DUE_SOON,
            vax("HS" to ("Jun 2024" to VaccineStatus.DONE),"FMD" to ("Jan 2025" to VaccineStatus.DUE_SOON)),"450 kg","Black")
    )
}